In [1]:
import os
if os.name != 'posix':
    %matplotlib ipympl
else:
    %matplotlib notebook
import scipy.constants as sc
from scipy.optimize import fsolve

import numpy as np
import cmath
import matplotlib.pyplot as plt
import scipy.constants as sc
plt.rcParams.update({
    "text.usetex": True,
    'text.latex.preamble': r"\usepackage{amsmath} \boldmath"
})
import os
import h5py

print(os.getpid())
%cd ../../

import pylib.mix as mix
import pylib.measurement as mse

20407
/media/work/docs/codes/QuCF/scripts-py


In [2]:
# --- Launch to change cells' width ---
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

colors_ = ["blue", "red", "green", "gray", "black"]

from matplotlib import ticker
cmap_two_signs_= 'coolwarm'
cmap_two_signs_= 'Blues'
# cmap_two_signs_= 'Greys'
# cmap_two_signs_= 'Pastel1'
# cmap_two_signs_= 'flag'
# cmap_two_signs_= 'nipy_spectral'
# cmap_two_signs_= 'jet'
# cmap_two_signs_= 'seismic'
def fmt_(x, pos):
    a, b = '{:.2e}'.format(x).split('e')
    b = int(b)
    return r'${} \times 10^{{{}}}$'.format(a, b)

In [3]:
for i in range(10):
    plt.close()

In [33]:
# -----------------------------------------------------------------
# --- Selector ---
# -----------------------------------------------------------------
mix.reload_module(mix)

ns = 2
aa = 1.2

print()
print("ns \t{:d}".format(ns))
print("aa \t{:0.12e}".format(aa))

Ry = np.matrix([
    [np.cos(aa/2.), -np.sin(aa/2.)],
    [np.sin(aa/2.),  np.cos(aa/2.)]
])

print("\n--- Results ---")
U = np.eye(2)
for ii in range(1, 1<<ns):
    U   = Ry.dot(U)
    res = U.dot([1,0])
    print("j = {:d}: res = {:20.3e}|0> + {:20.3e}|1>".format(ii, res[0,0], res[0,1]))


ns 	2
aa 	1.200000000000e+00

--- Results ---
j = 1: res =            8.253e-01|0> +            5.646e-01|1>
j = 2: res =            3.624e-01|0> +            9.320e-01|1>
j = 3: res =           -2.272e-01|0> +            9.738e-01|1>


In [29]:
res

matrix([[0.825+0.j   , 0.   -0.565j]])

In [28]:
res[0,1]

-0.5646424733950353j

In [14]:
Ry

matrix([[0.825+0.j   , 0.   -0.565j],
        [0.   -0.565j, 0.825+0.j   ]])

In [9]:
Ry.dot([1,2])

matrix([[0.999-0.1j , 1.998-0.05j]])

In [15]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [17]:
Ry.dot(Ry)

matrix([[0.362+0.j   , 0.   -0.932j],
        [0.   -0.932j, 0.362+0.j   ]])